### ISSUE TITLE
A lot of the documented keybindings do not work

### ISSUE THREAD

**Issue by Cyberlane** [taigacute/ThinkVim#11]
# Problems summary

A lot of the documented keybindings/shortcuts do not work

## Environment Information

 * OS: MacOS 10.13.6 (17G7024)

 * neovim `:version` output:

```
NVIM v0.4.0-1015-gbabcf641e
Build type: Release
Lua
JIT 2.0.5
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
    1 health#coc#check
    2 ========================================================================
    3   - OK: Environment check passed
    4
    5   - OK: Build javascript found
    6   - OK: Service started
    7
    8 health#defx#check
    9 ========================================================================
   10 ## defx.nvim
   11   - OK: has("python3") was successful
   12   - OK: Python 3.6.1+ was successful
   13
   14 health#nvim#check
   15 ========================================================================
   16 ## Configuration
   17   - OK: no issues found
   18
   19 ## Performance
   20   - OK: Build type: Release
   21
   22 ## Remote Plugins
   23   - OK: Up to date
   24
   25 ## terminal
   26   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
   27   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   28   - INFO: $TERM_PROGRAM='iTerm.app'
   29   - INFO: $COLORTERM='truecolor'
   30
   31 health#provider#check
   32 ========================================================================
   33 ## Clipboard (optional)
   34   - OK: Clipboard tool found: macOS-clipboard
   35
   36 ## Python 2 provider (optional)
   37   - INFO: Using: g:python_host_prog = "/usr/local/bin/python"
   38   - INFO: Executable: /usr/local/bin/python
   39   - INFO: Python version: 2.7.16
   40   - INFO: pynvim version: 0.3.2
   41   - OK: Latest pynvim is installed.
   42
   43 ## Python 3 provider (optional)
   44   - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
   45   - INFO: Executable: /usr/local/bin/python3
   46   - INFO: Python version: 3.7.3
   47   - INFO: pynvim version: 0.3.2
   48   - OK: Latest pynvim is installed.
   49
   50 ## Ruby provider (optional)
   51   - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
   52   - INFO: Host: /usr/local/bin/neovim-ruby-host
   53   - OK: Latest "neovim" gem is installed: 0.8.0
   54
   55 ## Node.js provider (optional)
   56   - INFO: Node.js: v12.3.1
   57   - INFO: Neovim node.js host: /usr/local/Cellar/node/12.3.1/lib/node_modules/neovim/bin/cli.js
   58   - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
```

## How to reproduce the problem from neovim startup (Required!)

`gc` does nothing
`<Leader> + ff` opens a floating window, which lets me type but shows nothing else.
`<Leader> + tb` gives the error `SPC t b is undefined`

**Comment by taigacute** [comment]
@Cyberlane  do you installed `rg`

**Comment by taigacute** [comment]
any update?

**Comment by taigacute** [comment]
close

**Comment by Cyberlane** [comment]
Sorry, I've been away for a few days but I will be able to check on this tomorrow.

**Comment by taigacute** [comment]
ok  i reopen this issue

**Comment by Cyberlane** [comment]
I've updated, and now testing it out again.

The search works now, I did not have ripgrep, I made a wrong assumption that you were using `fd`, which is what I was using with `fzf` previously.

`<Leader> + tb` works fine now too.

---

`gc` does not comment
`gcc` does not uncomment

`gcgcc` will comment a line, but will not uncomment it. Maybe I am misunderstanding something on this one?

**Comment by taigacute** [comment]
@Cyberlane  gc should use textobject  `gciw` etc..  `gcc` will comment a line and type `gcc` again will uncomment line. you should know vim textobkect

**Comment by taigacute** [comment]
you should check this doc https://github.com/tyru/caw.vim/blob/master/doc/caw.txt

**Comment by Cyberlane** [comment]
@taigacute - I've been using VIM for 6 years year, and have never really read any books or tutorials, mostly learned by doing, and tweaking things by having it as my main IDE at work and home. So clearly this is one of the things I have missed out on, I'll read the doc you linked.

Thanks for your patience, and for the awesome config!

**Comment by taigacute** [comment]
@Cyberlane   i have fixed some bug, please update. you can use `local` to mange your plugins and vim settings.

**Comment by Cyberlane** [comment]
@Cyberlane - done!

Will you eventually allow for theme colorscheme customizations? I really like the config you have, but I much preferred the colorscheme I had before :)

**Comment by taigacute** [comment]
you can  use your colorscheme .only to change https://github.com/taigacute/ThinkVim/blob/master/core/themes/theme.vim#L22  or you can set it in local_settings.vim

**Comment by Cyberlane** [comment]
Fantastic, thank you!

**Comment by taigacute** [comment]
no thanks. by the way . do you got error when you use `;+m`

**Comment by Cyberlane** [comment]
Yeah, when I use `;+m` I get `[denite] denite failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.`

Do I need to run update, or is that done each time I open vim (much like the install) ?

**Comment by taigacute** [comment]
yes you should run `:UpdateRemotePlugins` for defx and denite ,cause they call the python rpc of neovim.

**Comment by Cyberlane** [comment]
I ran the update, closed and re-opened VIM and it still isn't working.

**Comment by Cyberlane** [comment]
How do you make those gifs showing the key presses? I could make one of those to try show what I am doing - maybe I am doing something incorrectly.

**Comment by taigacute** [comment]
@Cyberlane  can you `leader +e` to call defx, then `;+m` call denite. maybe you will got some error.then run command `:UpdateRemotePlugins` if you see `[defx.nvim,denite]` .its success.
i ask for Shougo that dein authoer .she said the call dein#init function will call dein#remote_plugins function. this function will register the plugin to rpc. but dont know why .i got the same info

**Comment by Cyberlane** [comment]
I have done `leader + e` and am on the defx, I pressed `;+m` and I got the same error.
I ran `:UpdateRemotePlugins` and I got the following:

```
remote/host: python3 host registered plugins ['defx', 'denite']
remote/host: generated rplugin manifest: ~/.local/share/nvim/rplugin.vim
```

What should this do?

**Comment by taigacute** [comment]
successed
