### ISSUE TITLE
Your Sponsor button is broken

### ISSUE THREAD

**Issue by dewoller** [taigacute/ThinkVim#12]
# Problems summary
I clicked on your github sponsor button, but it was broken. 

![Selection_013](https://user-images.githubusercontent.com/799531/59483093-1dafeb00-8eaf-11e9-90c8-bc8b474bf598.jpg)

I really like your opinionated collection of vim goodness.  Very well curated, thanks so much!

**Comment by taigacute** [comment]
@dewoller   thanks bro . i just want share a reasonable configuration，it has rich features and fatest startup. The init file should not be too long, it is difficult to maintain。 i didnt set the sponsor.so its broken

**Comment by taigacute** [comment]
@dewoller   i have fixed sponsor button. please check
