### ISSUE TITLE
Documentation:  How to get rid of >>> git attributions

### ISSUE THREAD

**Issue by dewoller** [taigacute/ThinkVim#13]
## What is your expect?

I was hoping I could figure out how to turn off the ghostly line by line git attribution, the thing that pops up on every new line, prefixed by >>>.  I turned off everything I could find in the configuration related to git but it still persists.  

![Selection_014](https://user-images.githubusercontent.com/799531/59483191-97e06f80-8eaf-11e9-8ad3-ebb5d7ca2907.jpg)

**Comment by taigacute** [comment]
if you dont like this ,you can set  false https://github.com/taigacute/ThinkVim/blob/master/coc-settings.json#L18

**Comment by taigacute** [comment]
by the way . i think plugins should be lazyload according demand。too many normal load plugins should make vim slowly. now i have set 61 plugins in thinvim. startuptime of empty file is 40~60ms.

**Comment by dewoller** [comment]
Thanks so much.  Yes, the lazy load is excellent.  I need to look more into coc.

**Comment by taigacute** [comment]
no thanks. i am a member of coc team:)

**Comment by taigacute** [comment]
@dewoller  coc has support R language pls check https://github.com/neoclide/coc-r-lsp
