### ISSUE TITLE
:FZF not working

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#14]
# Problems summary
`:FZF` or `<SPC> ff` giving the error below.

`Error detected while processing function Fzf_dev[25]..fzf#run[64]..<SNR>93_execute_term[3]..<SNR>93_split[9]..FloatingFZF:
line    1:
E117: Unknown function: nvim_create_buf
E15: Invalid expression: nvim_create_buf(v:false, v:true)
Press ENTER or type command to continue`

## Environment Information

 * OS: MacOs 10.13.2

 * neovim `:version` output:
`NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
`
   34 ## terminal
   33   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
   32   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   31   - INFO: $TERM_PROGRAM='iTerm.app'
   30   - INFO: $COLORTERM='truecolor'
   29
   28 health#provider#check
   27 ========================================================================
   26 ## Clipboard (optional)
   25   - OK: Clipboard tool found: macOS-clipboard
   24
   23 ## Python 2 provider (optional)
   22   - INFO: Using: g:python_host_prog = "/usr/bin/python"
   21   - INFO: Executable: /usr/bin/python
   20   - INFO: Python version: 2.7.10
   19   - INFO: pynvim version: 0.3.2
   18   - OK: Latest pynvim is installed.
   17
   16 ## Python 3 provider (optional)
   15   - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
   14   - INFO: Executable: /usr/local/bin/python3
   13   - INFO: Python version: 3.7.3
   12   - INFO: pynvim version: 0.3.2
   11   - OK: Latest pynvim is installed.
   10
    9 ## Ruby provider (optional)
    8   - INFO: Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    7   - INFO: Host: /usr/local/bin/neovim-ruby-host
    6   - OK: Latest "neovim" gem is installed: 0.8.0
    5
    4 ## Node.js provider (optional)
    3   - INFO: Node.js: v12.4.0
    2   - INFO: Neovim node.js host: /Users/serdar.simsek/.config/yarn/global//node_modules/neovim/bin/cli.js
    1   - OK: Latest "neovim" npm/yarn package is installed: 4.5.0`

## How to reproduce the problem from neovim startup (Required!)

 1. Open a java file
 2. Type `:FZF` or `<SPC> ff`
 3. Error

## Screenshot (if possible)
![Screen Shot 2019-06-14 at 13 37 47](https://user-images.githubusercontent.com/7443948/59507044-1df9b780-8eaa-11e9-8182-8f53cf3cbdfd.png)

**Comment by taigacute** [comment]
@emeentag   the neovim must > = 0.4.0 .

**Comment by emeentag** [comment]
@taigacute thx for the quick reply. Wen i try to instal that one i am getting errors and it stops to install. 
`Last 15 lines from /Users/serdar.simsek/Library/Logs/Homebrew/neovim/21.cmake:
   used as include directory in directory /tmp/neovim-20190614-27197-12fe110/runtime
   used as include directory in directory /tmp/neovim-20190614-27197-12fe110/runtime
   used as include directory in directory /tmp/neovim-20190614-27197-12fe110/runtime
   used as include directory in directory /tmp/neovim-20190614-27197-12fe110/runtime
   used as include directory in directory /tmp/neovim-20190614-27197-12fe110/runtime
   used as include directory in directory /tmp/neovim-20190614-27197-12fe110/runtime
   used as include directory in directory /tmp/neovim-20190614-27197-12fe110/runtime
LIBLUV_LIBRARY (ADVANCED)
    linked by target "libnvim" in directory /tmp/neovim-20190614-27197-12fe110/src/nvim
    linked by target "nvim-test" in directory /tmp/neovim-20190614-27197-12fe110/src/nvim
    linked by target "nvim" in directory /tmp/neovim-20190614-27197-12fe110/src/nvim

-- Configuring incomplete, errors occurred!
See also "/tmp/neovim-20190614-27197-12fe110/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/neovim-20190614-27197-12fe110/build/CMakeFiles/CMakeError.log".

READ THIS: https://docs.brew.sh/Troubleshooting`

**Comment by taigacute** [comment]
@emeentag  you should install cmake and some depends package . https://github.com/neovim/neovim/wiki/Installing-Neovim

the easy way you can download the Asserts, and set the `neovim/bin` into your` $PATH`

**Comment by emeentag** [comment]
Thx @taigacute i solved the problem by downloading the nightly release from github:

**Steps:**
1. Goto: https://github.com/neovim/neovim/releases
2. Select the version which is greater than `>= 0.4.0`
3. Put it  to one of your usr directory.
4. Create an alias for nvim to the path wher you save the nvim bin folder. i.e`~/nvim-osx64/bin/nvim`
 

Thanks.

**Comment by taigacute** [comment]
@emeentag  this is my way `export PATH="/Users/pendragon/neovim/bin:$PATH"`
