### ISSUE TITLE
启动界面显示空文件，而不是最近打开文件

### ISSUE THREAD

**Issue by Azureki** [taigacute/ThinkVim#15]
# Problems summary
启动`neovim`，界面显示空文件，而不是如`readme`中展示的一样显示**最近打开的文件**。

## How to reproduce the problem from neovim startup (Required!)
1. 使用**appimage**(因为我装了旧版0.3.7的neovim）。
2. git clone 本项目
3. 打开几个文件
4. 直接启动，后面不跟文件名

## Screenshot (if possible)

<img width="633" alt="image" src="https://user-images.githubusercontent.com/22387028/59511581-3d640500-8ee9-11e9-8c8d-3d2a8243312c.png">

## Environment Information

 * OS: linux
 * terminal: konsole

 * neovim `:version` output: 

```
:version
NVIM v0.4.0-1021-gdd21cd2a4                                                                                           
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno
-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fd
iagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI
_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src
 -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neo
vim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-4e58cf17-1f4e-4a15-98d9-1c839ab3251d

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
   应该不影响？
   * python2: WARNING: Unexpected Python version. This could lead to confusing error messages.
   * ruby: WARNING: `neovim-ruby-host` not found.
   * nodejs: WARNING: Missing "neovim" npm (or yarn) package.

**Comment by taigacute** [comment]
`leader+s` 打开startify。为了提高vim的速度。我基本上懒加载了很多插件。

**Comment by Azureki** [comment]
噗，原来是这样……

谢谢解答。
（话说回来速度好快呀

**Comment by taigacute** [comment]
@Azureki  neovim 版本升级下。不然会报错很多功能。

**Comment by Azureki** [comment]
嗯，知道，我现在用的是appimage测试，版本是0.4.0的，floatwindow可用。

安装的neovim是和系统一起升级，所以还是0.3.7.……（

**Comment by taigacute** [comment]
终端最好找个支持emoji的。或者你把emoji的地方换成utf8的符号

**Comment by Azureki** [comment]
@taigacute 
233，是右上角的图标显示错了吗？这个好像是`Operator Mono`的连字。

linux好像没有比较漂亮的terminal。我用的是kde桌面自带的`konsole`，也是支持emoji的。  
显示错误是因为我截图时terminal没用下载的`fira nerd font`，用这个是可以正常显示文件图标的。

至于`Operator Mono`的话应该需要我自己patch才行（  
换成unicode是有一个开关切换吗？还是要手动一个个替换呢？

**Comment by Azureki** [comment]
话说所有安装的插件都在 `~.config/nvim/core/plugins` 下吗？  
我在找了一下没有发现`vim-devicons`，但是图标可以显示。

**Comment by taigacute** [comment]
插件在dein里的toml文件，

**Comment by Azureki** [comment]
唔？这个文件只是说有哪些插件吧，可是`vim-devicons`插件安装的位置是什么呢？  
我简单找了一下似乎只有`~.config/nvim/core/plugins`这个文件夹，但是里面没有`vim-devicons`

**Comment by taigacute** [comment]
因为这个插件没啥设置的。其他插件只是依赖它提供的方法。toml文件里也会放一些插件的设置，不过是简单的设置，复杂的会提出来在plugins下单独建个文件

**Comment by Azureki** [comment]
明白了，原来是这样。

之前一直在本地看的，才发现 plugins 下面的插件都是修改过的。
