### ISSUE TITLE
cannot start denite until a todo.sqlite database is created.

### ISSUE THREAD

**Issue by Azureki** [taigacute/ThinkVim#17]
# Problems summary

Besides preconditions referred in `readme`, a `todo.sqlite` database should be created.

## How to reproduce the problem from neovim startup (Required!)

 1. git clone this repo, start neovim
 2. start denite => fail. 
 3. run `:checkhealth` => result: denite is ok
 4. run `:UpdateRemotePlugins`. 
 5. start denite again => fail.

error messages: 
```
denite failed to load. 
sqlite3.OperationalError: unable to open database file
IN FILE: 
~/.cache/dein/repos/github.com/chemzqm/todoapp.vim/rplugin/python3/denite/source/todo.py
Line 33
```
Open the referred file and find: 
``` python
db = os.path.expanduser('~/.todo/todo.sqlite')
conn = sqlite3.connect(db)
```

Create this database, run denite again. => success.

**Comment by taigacute** [comment]
@Azureki   No  you should use this command to create database `TodoInit`

**Comment by Azureki** [comment]
哦，[chemzqm/todoapp.vim](https://github.com/neoclide/todoapp.vim)也提到了。  

那么解决方法如下：先安装`todoapp.vim`插件，再运行`:TodoInit`，然后就可以打开`denite`（

**Comment by taigacute** [comment]
差不多。`localleader+d+a` 添加todo

**Comment by Azureki** [comment]
不过，我想了想，denite不依赖Todoapp启动是不是更好呢？  
还没学vim脚本，不知道是否麻烦。

**Comment by taigacute** [comment]
denite 不依赖todoapp。。todoapp依赖denite。

**Comment by Azureki** [comment]
唔，我的意思是，`localleader + m`启动`deinite_menu`会出错，要先安装`todoapp`才行。
这样的话，即使不需要`todo`功能，但是为了使用`denite_menu`也需要安装`todoapp`。

**Comment by taigacute** [comment]
todoapp 其实挺鸡肋的这个。可以有更好的选择。而且也不是强需求。注释掉就行了

**Comment by taigacute** [comment]
我刚注释掉了，昨天改动了很多。不适用toml文件管理插件，是用yaml文件管理。添加local文件夹存放自己的配置。和thinkvim分开。

**Comment by Azureki** [comment]
好，没有问题了。
