### ISSUE TITLE
source_file函数中一个路径似乎错了

### ISSUE THREAD

**Issue by Azureki** [taigacute/ThinkVim#18]
[deinrc.vim的63行](https://github.com/taigacute/ThinkVim/blob/cc79ca174f26f2f227d384afebfc68a45611c722/core/deinrc.vim#L63)，文件夹`/config/`不存在，应该是`/core/`。

----

最新版支持自定义配置了，于是试了一下，然后报错，在[vimrc的83行](https://github.com/taigacute/ThinkVim/blob/cc79ca174f26f2f227d384afebfc68a45611c722/core/vimrc#L83)。
发现这里用了一个函数，而这个函数里的一个路径有`/config/`这个不存在的文件夹。

**Comment by taigacute** [comment]
@Azureki  改了。

**Comment by taigacute** [comment]
@Azureki  我知道了source函数写错了。你更新下就没事了。

**Comment by Azureki** [comment]
好。  

开始是提示没有这个函数。
然后我发现在`deinrc.vim`中，于是复制进`vimrc`，还是错。发现`config`错了。

看了下最新的代码。似乎我理解错了，`source_file`这个函数本来就不是为了启用自定义配置文件的？

----
收获就是知道加了`s:`变成局部变量`script-variable`233（

**Comment by taigacute** [comment]
不是 是加载文件的不知道怎么多弄了一个。
