### ISSUE TITLE
[coc.nvim] compiled javascript file not found!

### ISSUE THREAD

**Issue by xiaomabetter** [taigacute/ThinkVim#19]
Download dein plugin management wait a moment
:!git clone https://github.com/Shougo/dein.vim /Users/xiaoma/.config/nvim/repos/github.com/Shougo/dein.vim

正克隆到 '/Users/xiaoma/.config/nvim/repos/github.com/Shougo/dein.vim'...
[coc.nvim] compiled javascript file not found!

## Environment Information
 * OS:
macos 10.12.6 
neovim v0.4.0

**Comment by taigacute** [comment]
@xiaomabetter  coc没有安装上，最好是翻墙或者换个安装方式。
