### ISSUE TITLE
Create a tutorial video ？

### ISSUE THREAD

**Issue by taigacute** [taigacute/ThinkVim#20]
maybe create a tutorial about thinkvim 。will be nice ？

**Comment by emeentag** [comment]
There is a video out there on youtube but it is not english. An english one could be really nice. Also there should be more color schema options. Or we should think a better way to customize it.

**Comment by taigacute** [comment]
@emeentag  you can change the colorschema by `leader+ f+c`

**Comment by emeentag** [comment]
> @emeentag you can change the colorschema by `leader+ f+c`

Thanks a lot works great but it is not changing the tabs color. I think it could be also fixed with airblade properties but i am not sure. Also we should update the doc section `ColorScheme` for this shortcut. And for the Defx usage we should definetly give another option like Nerdtree out of the box. Still there are some essential behaviours are missing. It is ok you can do many thing by calling methods but most of the time they are not working properly. i.e https://github.com/Shougo/defx.nvim/issues/87#issuecomment-503025538

**Comment by taigacute** [comment]
@emeentag  i had provide the nerdtree .but the i found the defx is more useful than nerdtree. i will add it agin.

**Comment by emeentag** [comment]
@taigacute thx a lot. This does not mean we can couple or triple or plugins etc. But you know there are some out there which are essentials and basics for most of the vim-ers. And as i see `defx` is new one so making a new one by default and as only option does not good to have in very first step. So mature plugins always can be attractive and a good point to start making a transition to a new one. Do you want me to create a feature request for it?

**Comment by taigacute** [comment]
@taigacute   i have added the nerdtree .please update. the key is `localleader + e`

**Comment by emeentag** [comment]
@taigacute thx a lot. it is better to create a feature request ticket for this change in a specific title. You know if people search it on internet this type of changes will be liste. No body expect this kind of change is implemented under a video tutorial ticket. Better to create separate tickets in next time.

**Comment by taigacute** [comment]
i check the problem. you need open the current file in defx?

**Comment by emeentag** [comment]
Exactly but it is not convenient. In nerd tree it is just `map <leader>r :NERDTreeFind<cr>` thats it

**Comment by taigacute** [comment]
@emeentag  right?
![ranger](https://user-images.githubusercontent.com/41671631/59677635-e74ed480-91fc-11e9-96c3-d7e003ac0a94.gif)

**Comment by emeentag** [comment]
Exactly! Anyway we are moving away the context  of the topic :D thx @taigacute

**Comment by taigacute** [comment]
i used `leader+ e`. it can do this thing.

**Comment by emeentag** [comment]
Yeah but when you make a file search and then select a file and then locate to that file it is massing up the things. I already swtich to nerdtree so i need time to try defx

**Comment by taigacute** [comment]
![ranger](https://user-images.githubusercontent.com/41671631/59678396-e74fd400-91fe-11e9-8f3d-bfa3a67515d1.gif)

**Comment by taigacute** [comment]
i think this issue should be close and recreate a new issue about video
