### ISSUE TITLE
local settings to live outside of git repo or ignored

### ISSUE THREAD

**Issue by Cyberlane** [taigacute/ThinkVim#21]
## What is your expect?

It would be great if the `local_settings.yml` could live outside of the git repo, or if they are ignored, along with extra files in the colors folder. Currently, each time I want to pull changes from your repo, I need to do git stash, then pull, then pop the stash. It would be great if I didn't need to worry about stashing.

**Comment by emeentag** [comment]
Hi @Cyberlane , forking the repo could be better for you. Personally i did it.

**Comment by Cyberlane** [comment]
@emeentag you are probably right, that way I don't need to worry if this repo disappears randomly one day.

**Comment by taigacute** [comment]
you can fork this repo. and local setting can live out the repo .but i need a path that local folder position。

**Comment by Cyberlane** [comment]
I will go with forking, it makes the most sense at the moment for me :)

**Comment by taigacute** [comment]
you can change this path for vim settings https://github.com/taigacute/ThinkVim/blob/master/core/vimrc#L7

and this path is local plugins yaml 
https://github.com/taigacute/ThinkVim/blob/master/core/deinrc.vim#L14
