### ISSUE TITLE
Error when opening Go file

### ISSUE THREAD

**Issue by Cyberlane** [taigacute/ThinkVim#22]
# Problems summary

When I open a Golang file, I get an error.

## Environment Information

 * OS: MacOS

 * neovim `:version` output: 0.4.0-1015

 * `:checkhealth` or `:CheckHealth` result(neovim only):

All green

## How to reproduce the problem from neovim startup (Required!)

I have a file located in `~/Projects/Cyberlane/simple-go/main.go`
I have ENV `export GOPATH="$HOME/Projects"`
When I open `main.go` with vim, I get the following error:

```
Error detected while processing function <SNR>67_register[9]..go#lsp#DidOpen:
line   19:
E117: Unknown function: sendMessage
E15: Invalid expression: l:lsp.sendMessage(l:msg, l:state)
Press ENTER or type command to continue
```

The content of the file is extremely tiny

```golang
package main

import "fmt"

func main() {
  fmt.Println("Hello, world.")
}
```

I am new to Go, I thought I would try it out since this VIM config is already setup for it. Am I doing something wrong, or is this a bug?

**Comment by taigacute** [comment]
@Cyberlane  did you set the lsp for go?

**Comment by Cyberlane** [comment]
As I said, I'm new to go... so I have no idea what that is.

I have done `brew install go`, set that environment variable and then tried to follow a tutorial for a simple app to go familiar with the language.

**Comment by taigacute** [comment]
you should add the gopls into the `coc-settings.json`like  
```json
 "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
```

**Comment by taigacute** [comment]
more about the gopls you should check this link https://github.com/golang/go/wiki/gopls

**Comment by Cyberlane** [comment]
Ah, I assumed all of the `coc-settings.json` were pre-configured for both Go and JS :)

I will add that now, and install `gopls` and see how it goes...

**Comment by taigacute** [comment]
maybe you should to know coc.and how to work, the `coc-settings.json` like vscode settings.jsons. you can add any language lsp into the `coc-settings.json` like c go c++ and so on .the js server is coc-tsserver which coc  provide it . 

this is coc github https://github.com/neoclide/coc.nvim

check this link about lsp. [what is lsp]( https://docs.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol?view=vs-2019)

and this my coc-settings.json . 
```
{
    "suggest.triggerAfterInsertEnter": false,
    "suggest.timeout": 500,
    "suggest.noselect": false,
    "suggest.detailField":"abbr",
    "suggest.snippetIndicator": "🌟",
    "suggest.triggerCompletionWait": 100,
    "suggest.echodocSupport": true,
    "suggest.completionItemKindLabels": {
        "keyword": "\uf1de",
        "variable": "\ue79b",
        "value": "\uf89f",
        "operator": "\u03a8",
        "function": "\u2A15",
        "reference": "\ufa46",
        "constant": "\uf8fe",
        "method": "\uf09a",
        "struct": "\ufb44",
        "class": "\uf0e8",
        "interface": "\uf417",
        "text": "\u2663",
        "enum": "\uf435",
        "enumMember": "\uf02b",
        "module": "\uf530",
        "color": "\ue22b",
        "property": "\ue624",
        "field": "\uf6a6",
        "unit": "\uf475",
        "event": "\ufacd",
        "file": "\uf723",
        "folder": "\uf114",
        "snippet": "\ue60b",
        "typeParameter": "\uf728",
        "default": "\uf29c"
    },
    //diagnostic
    "diagnostic.signOffset": 9999999,
	"diagnostic.errorSign": "●",
	"diagnostic.warningSign": "●",
    "diagnostic.displayByAle": false,
    "diagnostic.refreshOnInsertMode": true,
    //git
    "git.enableGutters": true,
    "git.addGlameToBufferVar": true,
    "git.addGlameToVirtualText": true,
    "git.virtualTextPrefix": " ❯❯❯ ",
    "git.addedSign.hlGroup": "GitGutterAdd",
    "git.changedSign.hlGroup": "GitGutterChange",
    "git.removedSign.hlGroup": "GitGutterDelete",
    "git.topRemovedSign.hlGroup": "GitGutterDelete",
    "git.changeRemovedSign.hlGroup": "GitGutterChangeDelete",
    "git.addedSign.text":"▎",
    "git.changedSign.text":"▎",
    "git.removedSign.text":"▏",
    "git.topRemovedSign.text": "▔",
    "git.changeRemovedSign.text": "▋",
    //Snippet
    "coc.preferences.snippetStatusText": "Ⓢ ",
    //tslint
    "tslint.autoFixOnSave": true,
    //prettier
    "coc.preferences.formatOnSaveFiletypes": ["css","markdown"],
    "prettier.statusItemText": "ⓟ ",
    "prettier.eslintIntegration": true,
    "prettier.tslintIntegration": true,
    "prettier.stylelintIntegration": true,
    //emmet
    "emmet.includeLanguages": {"vue-html": "html", "javascript": "javascriptreact"},
    //python
    "python.autoComplete.addBrackets": true,
    // eslint
    "eslint.filetypes": ["javascript", "javascript.jsx", "javascriptreact"],
    "eslint.autoFix": true,
    "eslint.autoFixOnSave": true,
    //golang
    "languageserver": {
            "golang": {
                "command": "gopls",
                "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
                "filetypes": [
                    "go"
                ]
            },
        "dockerfile": {
                "command": "docker-langserver",
                "filetypes": [
                    "dockerfile"
                ],
                "args": [
                    "--stdio"
                ]
            },
            "efm": {
                "command": "efm-langserver",
                "args": [],
                "filetypes": [
                    "vim",
                    "markdown"
                ]
            }
        }
}

```

**Comment by Cyberlane** [comment]
I briefly started to use CoC about a month ago, prior to that I was using:

```
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
```

and prior to that I was using `YouCompleteMe`, but it was so slow, so I stopped using it.
I do understand what a language server is in the context of VIM (although, I honestly am not used to seeing it abbreviated to `lsp`), so I had assumed you meant it was something specific to Golang :)

It's up and working now, the only errors I get are from `gopls`, thanks for the help! :)

**Comment by taigacute** [comment]
`vim-jsx-imporve` better than that plugins. i have add some feature into this plugin. gopls has som problem .its not stable . gopls has developing.

**Comment by Cyberlane** [comment]
@taigacute I just noticed that when I do indent in Go files, it does tabs instead of spaces. If I do indent in a JS file, it does spaces just fine.

Is there a per-language setting I am missing? I assumed the following were enough:

```vim
set tabstop=2
set shiftwidth=2
set expandtab
```

**Comment by taigacute** [comment]
cause go code indented with tabs . it not support space. i have set https://github.com/taigacute/ThinkVim/blob/master/after/ftplugin/go.vim

**Comment by Cyberlane** [comment]
Ah... I assumed it would be like C and not care so much. Thanks for the info!

**Comment by taigacute** [comment]
i use this plugin for https://github.com/Yggdroot/indentLine  for indented. but this plugin doesnt support the code with tabs.
