### ISSUE TITLE
How can me make language diversity.

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#23]
## What is your expect?
In here i am 100% sure we can diverse the languages by adding out vim file or local settings for sure. But as i see know repo **seems** to dedicated for specifically `go`. But since i start to use it i like the idea and the organisation of the repo i felt like i am using it years. Easy to change anything in vim context again so you do not need to learn any new thing specifically to that repo.

And i easily implement LSP for `java`. And then also implement cTags for `groovy` for listing my class attributes and worked perfect. 

So you know most of the time for adapting your language to an editor with plugins need to apply many in-depended changes. 

In here i would like to discuss with you guys how can we make a structure to integrate different languages in this setup.

- For example by implementing java lsp you should run this command `:CocInstall coc-java` it is super easy to do but could make super sense i.e. `if we can provide a list with languages for Coc intiations.`

- Another thing after i implemented the lsp for java i see that my tag bar not worked for groovy so what i did. I search for it and update universal taglib with the .ctags of groovy then refresh my ctags on my project and also add some custome code to my `local_settings.vim` script and boom it worked. But again how can we make this in a single command or as a dependency of language activatio list that i mentioned above?

But again i would like to have these features again staying in vim context. I mean not introducing new data structures etc. 

Thanks.

**Comment by taigacute** [comment]
@emeentag  cause this repo is my config .i write the go python js react. this repo i want provide a samll and reasonable and fatest startup time configruation fram。 Programming language is so much，i cant add every language into this repo . i  wont make this repo to be a second `SpaceVim` you know its too heavy. you can add any language which you used by coc. its very easy. cause the coc is very stronger .i hope you can grasp this config .and edit it to be your own confiig .
not ThinkVim. its yours. a config that belong to you.

by the way ,i will add some practical feature plugins . cause these plugins can help anyone .

**Comment by taigacute** [comment]
The programming language used by most people is limited, and adding a lot of programming language support will make this repo very large, although it is easy to implement through coc. But each person who uses it does not want to see something unrelated to him appear in his configuration.

**Comment by emeentag** [comment]
Actually what i try to say here think about a dein window to list all available CoC lsps and make them available by selecting them?

**Comment by taigacute** [comment]
you can see this pic.the list is extensions that coc provide . 
![image](https://user-images.githubusercontent.com/41671631/59677017-8246af00-91fb-11e9-8eb5-380057ebe7e2.png)
but most of program languages coc does not provide. you need  config it in `coc-settings.json`
see this pic 
![image](https://user-images.githubusercontent.com/41671631/59677148-cafe6800-91fb-11e9-8b15-61e62e3ef193.png)
so  its very difficult to implement.  but for coc extensions ,you can use this extensions  https://github.com/fannheyward/coc-marketplace,it wil show all coc extensions in vim and you can select them to install
