### ISSUE TITLE
Error while initiating the NerdTree

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#24]
# Problems summary
Error while initiating the NerdTree 
Try to type `:NERDTreeToggle` or initiate with `<localleader> + e command` It is not autocompleted. And when you type and hit that command it shows the error in below.

## Environment Information

 * OS: Mac Os 10.13.2

 * neovim `:version` output: 
NVIM v0.4.0-1021-gdd21cd2a4
Build type: Release
LuaJIT 2.0.5

 * `:checkhealth` or `:CheckHealth` result(neovim only):
Everything is ok and green.

## How to reproduce the problem from neovim startup (Required!)

 1. Open nvim.
 2. Try to type `:NERDTreeToggle`
 3. It is not autocompleted. And when you hit type and hit that command it shows the error in below.
NOTE: After you initiated the nerd tree nvim starting to autocomplete it. Also you can see this error whit `<localleader> + e command`

By the way tree is working fine only thing is this error prints.

## Screenshot (if possible)
![Screen Shot 2019-06-18 at 12 56 50](https://user-images.githubusercontent.com/7443948/59677408-0e3fe300-91ca-11e9-8cee-e19163deaf0d.png)

**Comment by taigacute** [comment]
fiexed.  i miss a dot.

**Comment by emeentag** [comment]
I am seeing the same erorr after updating the change.

**Comment by taigacute** [comment]
@emeentag  fixed . my misstake.
