### ISSUE TITLE
Error while closing the tab

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#25]
# Problems summary
I am getting this error while closing a tab.

`E784: Cannot close last tab page`

## Environment Information

 * OS: Mac os 10.13

 * neovim `:version` output:
NVIM v0.4.0-1021-gdd21cd2a4
Build type: Release
LuaJIT 2.0.5

 * `:checkhealth` or `:CheckHealth` result(neovim only):
OK

## How to reproduce the problem from neovim startup (Required!)

 1. Open the a tab or more tab then select one of them.
 2. Try to close with <leader> + tc
 3. See the error out put.

**Comment by taigacute** [comment]
Please try `C-x`

**Comment by emeentag** [comment]
That works but we should update the document then.

**Comment by taigacute** [comment]
@emeentag  because `set hidden ` will  cause the `tabclose` didnt work. should remove the `tabclose`
