### ISSUE TITLE
Provide Ripgrep params to fzf + rg search

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#27]
## What is your expect?
Now when i use `<Leader> + fr` it opens a window and waiting my grep. So i am typing some text but i wanna filter them out according to file types. So i wanna apply -g or -t option of ripgrep but i do not know how can i do that on that window.

Help pls...

**Comment by taigacute** [comment]
please add it in there https://github.com/taigacute/ThinkVim/blob/master/core/plugins/fzf.vim#L27.and try it.

**Comment by emeentag** [comment]
Thx!
