### ISSUE TITLE
Class Preview in fzf not working 

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#28]
# Problems summary
Currently when i enter `<leader> + ff` and move over a class file i am not able to see the preview of the file. It was working before but suddenly disappear. I am getting the image below instead:
<img width="1146" alt="Screen Shot 2019-06-20 at 02 11 36" src="https://user-images.githubusercontent.com/7443948/59809510-29613e80-9301-11e9-934e-428a0a4c0163.png">

Not: `sudo gem install rouge` installed

## Environment Information

 * OS:
Mac Os 10.14.5

 * neovim `:version` output:
NVIM v0.4.0-1029-g93f8c2793
Build type: Release
LuaJIT 2.0.5

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#coc#check
    2 ========================================================================
    3   - OK: Environment check passed
    4
    5   - OK: Build javascript found
    6   - OK: Service started
    7
    8 health#nvim#check
    9 ========================================================================
   10 ## Configuration
   11   - OK: no issues found
   12
   13 ## Performance
   14   - OK: Build type: Release
   15
   16 ## Remote Plugins
   17   - OK: Up to date
   18
   19 ## terminal
   20   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
   21   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   22   - INFO: $TERM_PROGRAM='iTerm.app'
   23   - INFO: $COLORTERM='truecolor'
   24
   25 health#provider#check
   26 ========================================================================
   27 ## Clipboard (optional)
   28   - OK: Clipboard tool found: macOS-clipboard
   29
   30 ## Python 2 provider (optional)
   31   - INFO: Using: g:python_host_prog = "/usr/local/bin/python"
   32   - INFO: Executable: /usr/local/bin/python
   33   - INFO: Python version: 2.7.16
   34   - INFO: pynvim version: 0.3.2
   35   - OK: Latest pynvim is installed.
   36
   37 ## Python 3 provider (optional)
   38   - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
   39   - INFO: Executable: /usr/local/bin/python3
   40   - INFO: Python version: 3.7.3
   41   - INFO: pynvim version: 0.3.2
   42   - OK: Latest pynvim is installed.
   43
   44 ## Ruby provider (optional)
   45   - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
   46   - WARNING: `neovim-ruby-host` not found.
   47     - ADVICE:
   48       - Run `gem install neovim` to ensure the neovim RubyGem is installed.
   49       - Run `gem environment` to ensure the gem bin directory is in $PATH.
   50       - If you are using rvm/rbenv/chruby, try "rehashing".
   51       - See :help g:ruby_host_prog for non-standard gem installations.
   52
   53 ## Node.js provider (optional)

## How to reproduce the problem from neovim startup (Required!)

 1. <Leader> + ff
 2. Select a class and seeing the screen shot above.

**Comment by taigacute** [comment]
you should install rouge  `sudo gem install rouge`

**Comment by emeentag** [comment]
Issue was here to add `gem` `bin` directory into the path. It was written in output of `checkhealth` but somehow i missed that part. Thx!
