### ISSUE TITLE
Using the tagbar in a window like fzf or rg has

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#29]
## What is your expect?
I am not sure this is possible but it could be awsome if we can show the `tagbar` or `Vista` in a window like we are currently using for `fzf` and `ripgrep`.
i.e: <Leader> + tb can show a listing off class attributes etc. What ever the result of tagbar or vista.

**Comment by taigacute** [comment]
fzf and denite support outline .

**Comment by taigacute** [comment]
Please try `:Denite outline`

**Comment by emeentag** [comment]
Hi @taigacute thx for the reply. But i did not understand how this can work. But anyway i gave it a try and saw that:
```[denite]     conn = sqlite3.connect(db)
[denite] sqlite3.OperationalError: unable to open database file
[denite] Please execute :messages command.```

How can i create an sqlite db? I mean where should i create.

But even if i create i think it will not cover what i thought. You know the tagbar pane on the right, i wish to have it like a window of FZF or RG, so is this `:Denite outline` do this?

**Comment by taigacute** [comment]
why you got this. i comment `todoapp.vim` this plugin. because the `todoapp.vim`need sqlite databse . please check `plugins.yaml` .  `Denite outline ` will got the outline in floatwindow
![image](https://user-images.githubusercontent.com/41671631/59843908-1ba4cb00-938c-11e9-946b-943615a62174.png)

**Comment by emeentag** [comment]
Weird it is still in my `plugins.yaml`

```- repo: chemzqm/todoapp.vim
  on_cmd: [TodoAdd,TodoImport]
  on_source: denite.nvim
```

**Comment by taigacute** [comment]
comment it .

**Comment by emeentag** [comment]
Perfect. One thing more, when i try to update my fork with your current master, it shows me many conflicts i am solving all of them but the readme file is always appearing as a new conflict. It is super interesting.

**Comment by taigacute** [comment]
i found a interesting setting. used vista and fzf can do this 
![image](https://user-images.githubusercontent.com/41671631/59899542-adade180-9427-11e9-8060-6cedef74500e.png)

**Comment by emeentag** [comment]
Wovvv thats better perfect. `<leader> + fv` works perfect. Thanks @taigacute
