### ISSUE TITLE
PK: my vim config

### ISSUE THREAD

**Issue by tracyone** [taigacute/ThinkVim#3]
https://github.com/tracyone/vinux

**Comment by taigacute** [comment]
@tracyone  也很棒啊，不过我的主要是neovim。没仔细看 。太复杂了 个别拆分还是不太合理感觉

**Comment by taigacute** [comment]
close

**Comment by tracyone** [comment]
我的配置适合三大主流操作系统，vim和neovim，macvim，gvim等

**Comment by taigacute** [comment]
@tracyone  我没做那么多。不想做成项目级别。vim 还是要自己折腾才有意思。我这个只是提供个样例让大家摆脱冗长的配置。

**Comment by taigacute** [comment]
@tracyone  看到ycm就。。以前还行现在有点跟不上了。

**Comment by tracyone** [comment]
我这个配置最大特点是模块化+动态使能禁止模块，后者是你readme中提到的“模块化”所你具备的。真正的模块化，就应该可以方便的使能或者禁止，spacevim系列，spacemacs系列都可以，它们通过修改用户配置达到这个目的，而你的可能只是分开配置而已。

关于你提到的第2点，模块化也意味着不仅仅只有一个插件。

我这个配置的确有点大了，有接近130+插件及其配置。你说lazy load不够，鉴于我们两个配置插件数量级上的差距，我觉得还是挺多的，比如说有80个lazy load了。

其实百分之80都是插件及其配置，只不过放在不同地方以及能否配置好而已，这个对于很多人都是没啥问题，只是有没有时间找而已。

作为爱好者，肯定不止这些，自己写插件，自己封装大量函数。

**Comment by taigacute** [comment]
出发点是不一样的。我的配置只是我个人配置。你说的这些特点确实方便了大家入门。也渐渐的快变成了一个项目级别了。新手区阅读一个庞大的配置去调教是很吃力的。我只是提供小巧的模块配置。日常工作也忙没啥时间去折腾成项目。
