### ISSUE TITLE
Better to change <sg> - to <sv> in Denite Mode for creating the vertical split.

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#30]
## What is your expect?
Could be better if we can change keymapping `sg` to `sv` for creating the vertical split in denite mode. It makes more sense i think.

What you think?

**Comment by taigacute** [comment]
```
	nnoremap <silent><buffer><expr> sg   denite#do_map('do_action', 'vsplit')
	nnoremap <silent><buffer><expr> sv   denite#do_map('do_action', 'split')
```
sv has defined .

**Comment by taigacute** [comment]
change s to vsplit . i to split?  more like nerdtree. maybe better?

**Comment by emeentag** [comment]
But s and i has their own funcionality on vim in noraml mode. You mean <leader> + s/i?

**Comment by taigacute** [comment]
in denite mode .we can do this . because these keymap only work on `denite` filetype.

**Comment by taigacute** [comment]
change sv to vsplit, si to split
