### ISSUE TITLE
Can we add a debugger for the language that we use

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#31]
## What is your expect?
Currently i am using Java a language so there are several option to use a debugger for it but i do not know is there any plugin to manage debug sessions out there?

**Comment by taigacute** [comment]
you can debug server by https://github.com/neoclide/coc.nvim/wiki/Debug-language-server

**Comment by taigacute** [comment]
you can ask question about coc on coc gitter  https://gitter.im/neoclide/coc.nvim
