### ISSUE TITLE
如何设置defx的文件图标

### ISSUE THREAD

**Issue by ppnman** [taigacute/ThinkVim#32]
我在
https://github.com/taigacute/ThinkVim/blob/master/core/plugins/defx.vim
并没有看到文件图标的设置，但是首页的截图里面是有图标的。。请问是在哪里设置的呀？

**Comment by taigacute** [comment]
defx-icons 这个插件

**Comment by ppnman** [comment]
> defx-icons 这个插件

谢谢

**Comment by ppnman** [comment]
很抱歉又来叨扰您，但是我在defx那里没有找到解决办法。
我使用的是您的defx.vim的配置。
假如目前我已经打开了a.txt，再在defx中用`l`键打开了b.txt。
我想用`:bd`删除b.txt这个缓存区，但是运行完这个之后vim退出了！
但是我期望的行为是，还剩下一个a.txt的缓存区。
您能帮助我解决这个问题吗？谢谢了！

**Comment by taigacute** [comment]
你应该是没有关掉defx 。关掉defx在去删除buffer。

**Comment by ppnman** [comment]
> 你应该是没有关掉defx 。关掉defx在去删除buffer。

我本意是想让defx常驻左边的。难道不关闭defx就没法删除buffer吗？

**Comment by taigacute** [comment]
saurce code pro . 把那2个自动命令组去掉。做了判断删除buffer。

**Comment by ppnman** [comment]
> saurce code pro . 把那2个自动命令组去掉。做了判断删除buffer。

果然是字体的原因，尝试了很多nerdfont，目前只有saurce code pro工作良好。
defx的问题也解决了，谢谢大佬。
顺便说下：ThinkVim的配置真好看！

**Comment by taigacute** [comment]
看了你的statusline ，好像用的老配置。可以更新下。

**Comment by ppnman** [comment]
> 看了你的statusline ，好像用的老配置。可以更新下。

就是用的最新的配置，不过在你的基础之上修改了一下。嘿嘿。

**Comment by ppnman** [comment]
这里https://github.com/taigacute/ThinkVim/blob/6f2a5c0d425802cada4063e724cb13e89503e34e/core/plugins/lightline.vim#L82可以简化为`filter(range(1, bufnr('$')), 'buflisted(v:val)')`
