### ISSUE TITLE
 build a new statusline？

### ISSUE THREAD

**Issue by taigacute** [taigacute/ThinkVim#35]
The current statusline  is easy to get tired of aesthetics. All the statusline plugins don't have any intentions. I want to change it. I am hesitating. If you have any good idea ,pls tell me. it would be great if someone could implement it in pr.

**Comment by emeentag** [comment]
https://gitlab.com/dwt1/dotfiles this theme is best that i have ever seen. I do not know what the color codes are but we can definetly have look at it and the components as well.

**Comment by taigacute** [comment]
`onedark.vim`. the statusline is airline.  you can change the thinkvim colorscheme and lightline colorscheme to `onedark`.

**Comment by emeentag** [comment]
I tried but could not make it run, airline, syntax, lightline etc...

**Comment by taigacute** [comment]
download the `onedark.vim` then move to the colors folder. change the `theme/themes.vim` colorscheme onedark.   the default colorscheme folder of lightline has onedark theme. just edit the lightline.vim change the gruvbox9 to onedark

**Comment by emeentag** [comment]
https://github.com/emeentag/ThinkVim/commit/6e680416690de871ed672d014b3b543ce3eeab75

Please have look to this commit and the result here:
- airline is broken 
- tabs are broken: I am not able to open FZF file or nerdtree file in a new tab.
- Question: Do i need to install sheerun/vim-polyglot for syntax highlighting or do we have already a similar one.

**Comment by taigacute** [comment]
@emeentag  change the colorscheme , you can edit here https://github.com/taigacute/ThinkVim/blob/master/core/themes/theme.vim#L22,

if you want use airline you sould disable lightline.    

change the lightline colorscheme
https://github.com/taigacute/ThinkVim/blob/master/core/plugins/lightline.vim#L2

**Comment by emeentag** [comment]
@taigacute now i got it. It seems perfect now. regarding to `colorscheme` property i actually changing it in my local_settings.vim Now i got everything works.

**Question:** Do i need to install sheerun/vim-polyglot for syntax highlighting or do we have already a similar one.

Only thing  i think we should update status bar for NERDTree it looks a bit unusefull.
![Screen Shot 2019-06-27 at 13 53 01](https://user-images.githubusercontent.com/7443948/60264277-1ba05000-98e3-11e9-9656-f7d4f375d62b.png)

**Comment by taigacute** [comment]
the vim-polyglot provide manay syntax group for language. its too heavy . if the thinkvim doesnt have the syntax of your language .you can only add the plugin which provide the syntax  group of your language.

https://github.com/taigacute/ThinkVim/blob/master/core/plugins/lightline.vim#L51  . there should be add 
```
\      &filetype ==? 'nerdtree'           ? ' ' :
```

**Comment by taigacute** [comment]
by the way which language your write?

**Comment by emeentag** [comment]
It is Java + js. And coc is working fine i installed it but i am not sure i have the best highlighting for java.

**Comment by emeentag** [comment]
> the vim-polyglot provide manay syntax group for language. its too heavy . if the thinkvim doesnt have the syntax of your language .you can only add the plugin which provide the syntax group of your language.
> yes .you can add the config in local setting. because the local setting is sourced after thinkvimsettings. so localsetting will cover thinkvim settings。
> 
> https://github.com/taigacute/ThinkVim/blob/master/core/plugins/lightline.vim#L51 . there should be add
> 
> ```
> \      &filetype ==? 'nerdtree'           ? ' ' :
> ```

Worked perfectly.

**Comment by taigacute** [comment]
default neovim  support java file. i  dont write java. so didnt know the best syntax group for java.

**Comment by emeentag** [comment]
no worries i am ok with it it is much more than i need. I love ThinkVim and thanks for your collaboration. After i got use to it a bit more i am planning to record a tutorial per your tutorial task.

**Comment by taigacute** [comment]
thanks a lot. the suggest that the tutorila should have the usage of all plugins which thinkvim installed.
my english is not very well .if you can do it .very thanks.

**Comment by taigacute** [comment]
i  build a new statusline and tabline .remove lightline. if you want use lightline .you can uncomment `lightline` on `dein/plugins.yaml`
![image](https://user-images.githubusercontent.com/41671631/60397725-76a3a280-9b82-11e9-9ea7-ffbdc5f5d4c8.png)

**Comment by taigacute** [comment]
![image](https://user-images.githubusercontent.com/41671631/60412759-05590380-9c05-11e9-8541-c2d38e551a64.png)

i think its not perfect. but i dont have good idea...maybe need time ....

**Comment by taigacute** [comment]
build new statusline on dev branch. and i made a plugin call [spaceline.vim](https://github.com/taigacute/spaceline.vim)
![1](https://user-images.githubusercontent.com/41671631/60487885-022c4900-9cd3-11e9-84fe-7d70ac1882fa.png)
