### ISSUE TITLE
More comfortable keymap 

### ISSUE THREAD

**Issue by taigacute** [taigacute/ThinkVim#36]
if some keymaps doesnt comfortable  you can talk to here.

**Comment by taigacute** [comment]
1. Easymotion key.  now is use leaderkey to trigger  like `<Space><Space>w` , need double `<Space>`,so  its comfortable  or not?  what do you think?

**Comment by baIIoon** [comment]
I think it's good, but when something with visual mode kind of slow. Is there anyway to optimize easymotion

**Comment by taigacute** [comment]
easymotion only work on nmap.
```
if dein#tap('vim-easymotion')
            nmap <Leader><Leader>w <Plug>(easymotion-w)
	    nmap <Leader><Leader>f <Plug>(easymotion-f)
	    nmap <Leader><Leader>b <Plug>(easymotion-b)
endif

```
