### ISSUE TITLE
Error detected while processing function spaceline#spaceline#VimacsFilenameActive[20]..VimacsLineFname:

### ISSUE THREAD

**Issue by bsed** [taigacute/ThinkVim#40]
# Problems summary

Error detected while processing function spaceline#spaceline#VimacsFilenameActive[20]..VimacsLineFname:
im [-](url)

## Environment Information

 * OS: Xubuntu 19.04

 * neovim `:version` output: 

vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 27 2019 21:37:48)
Included patches: 1-1601
Compiled by kelvin@mb
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             +xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        -mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl  -lselinux -ldl   
 * `:checkhealth` or `:CheckHealth` result(neovim only):

## How to reproduce the problem from neovim startup (Required!)

![image](https://user-images.githubusercontent.com/10845087/60666633-11a9be80-9e9a-11e9-88ac-6ce525afe1c7.png)

**Comment by taigacute** [comment]
@bsed  please use neovim,and version >0.4.0

**Comment by bsed** [comment]
tks . solved

**Comment by taigacute** [comment]
@bsed  no thanks. you should create issue in [spaceline.vim](https://github.com/taigacute/spaceline.vim).and check out the config of spaceline.vim

**Comment by bsed** [comment]
sorry, i got i wrong.

**Comment by taigacute** [comment]
@bsed  dont say sorry. never mind. spaceline.vim provide some config .so you will got them in spaceline,vim . this repo doesnt provide spaceline config.
