### ISSUE TITLE
DefX not always opening in correct split

### ISSUE THREAD

**Issue by Cyberlane** [taigacute/ThinkVim#41]
# Problems summary

I am navigating around `defx` with the `hjkl` and using `l` to open a file.
Sometimes I can open a file, and it works just fine.
Sometimes I open a file, and instead of opening in the split I was in before going to `defx` it will open it in a random split.
Sometimes I open a file, and it will open it in the `defx` panel, and when I try use `ctrl+e =` it will resize all splits except the file opened in `defx`.

Previously I would use NerdTree and it behaved just fine for me, but I have been trying to use defx, and this problem really is bothering me. Am I using it incorrectly, or is this a bug?

## Environment Information

 * OS: `MacOS 10.14.5`

 * neovim `:version` output: `NVIM v0.4.0-dev`

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
1 health#defx#check
    2 ========================================================================
    3 ## defx.nvim
    4 ¦ - OK: has("python3") was successful
    5 ¦ - OK: Python 3.6.1+ was successful
    6
    7 health#coc#check
    8 ========================================================================
    9 ¦ - OK: Environment check passed
   10
   11 ¦ - OK: Javascript bundle found
   12 ¦ - OK: Service started
   13
   14 health#nvim#check
   15 ========================================================================
   16 ## Configuration
   17 ¦ - OK: no issues found
   18
   19 ## Performance
   20 ¦ - OK: Build type: Release
   21
   22 ## Remote Plugins
   23 ¦ - OK: Up to date
   24
   25 ## terminal
   26 ¦ - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
   27 ¦ - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   28 ¦ - INFO: $TERM_PROGRAM='iTerm.app'
   29 ¦ - INFO: $COLORTERM='truecolor'
   30
   31 health#provider#check
   32 ========================================================================
   33 ## Clipboard (optional)
   34 ¦ - OK: Clipboard tool found: macOS-clipboard
   35
   36 ## Python 2 provider (optional)
   37 ¦ - INFO: Using: g:python_host_prog = "/usr/local/bin/python"
   38 ¦ - INFO: Executable: /usr/local/bin/python
   39 ¦ - INFO: Python version: 2.7.16
   40 ¦ - INFO: pynvim version: 0.3.2
   41 ¦ - OK: Latest pynvim is installed.
   42
   43 ## Python 3 provider (optional)
   44 ¦ - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
   45 ¦ - INFO: Executable: /usr/local/bin/python3
   46 ¦ - INFO: Python version: 3.7.3
   47 ¦ - INFO: pynvim version: 0.3.2
   48 ¦ - OK: Latest pynvim is installed.
   49
   50 ## Ruby provider (optional)
   51 ¦ - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
   52 ¦ - INFO: Host: /Users/jusnel/.gem/bin/neovim-ruby-host
   53 ¦ - OK: Latest "neovim" gem is installed: 0.8.1
   54
   55 ## Node.js provider (optional)
   56 ¦ - INFO: Node.js: v12.2.0
   57 ¦ - INFO: Neovim node.js host: /Users/jusnel/n/lib/node_modules/neovim/bin/cli.js
   58 ¦ - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
```

## How to reproduce the problem from neovim startup (Required!)

Use `<leader>+e` to open `defx`, navigate around with `hjkl`, opening some sub-folders, and then some files. Make some splits with `:split` or `:vsplit`, and try open more files from `defx`.

**Comment by taigacute** [comment]
use `s` or `i` in defx to `split` or `vsplit`

**Comment by Cyberlane** [comment]
@taigacute that would open it in a new `split` or `vsplit` - but if I want to replace an existing split's content with another file selected in `defx`?

In NerdTree I had a binding that would `open current file in NerdTree`, which would move my cursor to that file in NerdTree, and then I could pick another file, open it, and it would replace that split with the new file.

**Comment by emeentag** [comment]
I experienced all these things @Cyberlane and found that it is the best to switch NerdTree. for me it takes too much time for using a simple file tree.

**Comment by Cyberlane** [comment]
@emeentag there was no performance issues in doing this? I really appreciate the massive performance I get with ThinkVim, but if I can go back to NerdTree without any performance concerns, I would be happy to put that into my config.

**Comment by emeentag** [comment]
I did not have any performance issues. We have a huge code base un here and test on it without any performance issues. In a codebase like defx responding sometimes with a delay 1 second. But nerdtree works perfect. Project contains variety of files like java css js less etc...

**Comment by taigacute** [comment]
you can try to uncomment this keymap  https://github.com/taigacute/ThinkVim/blob/master/core/plugins/allkey.vim#L181

and use `localleader+a`,  please test it.

**Comment by taigacute** [comment]
@Cyberlane  in allkey.vim  please use add this . you can use `localeader+a` to find the currentfile in defx
```viml
if dein#tap('defx.nvim')
        nnoremap <silent> <Leader>e
                \ :<C-u>Defx -resume -toggle -buffer-name=tab`tabpagenr()`<CR>
        nnoremap <silent> <LocalLeader>a
				\ :<C-u>Defx -search=`expand('%:p')` `getcwd()`<CR>
endif
```

**Comment by Cyberlane** [comment]
@taigacute sorry for slow replies, I am at work trying to use VIM to edit code, at the same time as reporting these issues I find :)

**Comment by Cyberlane** [comment]
@emeentag I think I am going to copy your config for my work machine, and run NerdTree just so I can continue to feel productive at the office, thanks!

@taigacute your `<LocalLeader> a` snippet works great! I will play around a bit more with defx on my personal machines, but for the office machine I am finding this slows me down a bit too often.

**Comment by emeentag** [comment]
@Cyberlane sure feel free to have it. It might not be the best but for me it feels perfect with ThinkVim structure.

**Comment by Cyberlane** [comment]
Closing the issue now, as it seems there is no real issue with ThinkVim, and it is more about how DefX works. The solution is to better understand defx, make more kind bindings, and work more the way defx wants you to work (or use another File Manager).

**Comment by taigacute** [comment]
it depends on you . you can add nerdtree in your local_plugin.yaml . i have nedtree config in plugins folder.

**Comment by Cyberlane** [comment]
@taigacute I tried that, and it did not auto install anything. Perhaps it is cached and not checking if there is new content in that file? I will experiment a bit with it this evening.

**Comment by taigacute** [comment]
ADD these into your local_plugins.yaml
```
- repo: tiagofumo/vim-nerdtree-syntax-highlight
  hook_add: |
    let g:NERDTreeSyntaxDisableDefaultExtensions = 1
    let g:NERDTreeDisableExactMatchHighlight = 1
    let g:NERDTreeDisablePatternMatchHighlight = 1
    let g:NERDTreeSyntaxEnabledExtensions = ['go', 'py', 'html', 'css', 'jsx', 'js', 'vim','json','md','c','cpp','java','php','groovy']
- { repo: Xuyuanp/nerdtree-git-plugin, on_source: nerdtree }
```
then add these into your local_settings.vim
```
if dein#tap('nerdtree')
        "nerdtree
        nnoremap <silent><localleader>e :NERDTreeToggle <CR>
        nnoremap <silent> <localleader>f :NERDTreeFind<CR>
endif
```

**Comment by Cyberlane** [comment]
![image](https://user-images.githubusercontent.com/1614416/60975679-a42fdf00-a32c-11e9-9768-1272835188f3.png)

and

![image](https://user-images.githubusercontent.com/1614416/60975717-b4e05500-a32c-11e9-9d6d-6803e9bf27d1.png)

It does not seem to be loading the `/core/local/local_plugins.yaml` file. I am not sure if this is perhaps related to the issue though:

![image](https://user-images.githubusercontent.com/1614416/60976191-8b73f900-a32d-11e9-9565-d21e47360232.png)

Does `denite_emnu.vim` need the local plugin path updated?

**Comment by Cyberlane** [comment]
Strange, it must have been some type of caching issue as it works fine on my machines at home.
I will clear the cache on the machine at the office tomorrow, and hopefully it will be okay.

Thanks again for the help!

**Comment by taigacute** [comment]
i set the auto cache.but i dont sure it works well. please try to recache runtimepath.

**Comment by Cyberlane** [comment]
I had to remove the dein cache folder, and then it worked just fine.
