### ISSUE TITLE
处理 function <SNR>59_register[9]..go#lsp#DidOpen 时发生错误:

### ISSUE THREAD

**Issue by DestinyWang** [taigacute/ThinkVim#43]
第   19 行:
E117: Unknown function: sendMessage
E15: 无效的表达式: l:lsp.sendMessage(l:msg, l:state)

![image](https://user-images.githubusercontent.com/17758731/61345921-9aa4fa80-a889-11e9-80b6-3dd2578e718a.png)

**Comment by taigacute** [comment]
安装gopls，注册gopls到coc-settings.json
