### ISSUE TITLE
How can i remove a plugin?

### ISSUE THREAD

**Issue by AlessandroChen** [taigacute/ThinkVim#44]
I have deleted lines in dein/plugins.yaml, but it didn't work.

Any help please?

**Comment by taigacute** [comment]
just recache。`call dein#recache_runtimepath()` or use menu `;+m` then choose dein choose recache runtimepath

**Comment by taigacute** [comment]
@AlessandroChen  by the way .i tested it, just use `gcc` to comment a plugin, then reopen nvim.it doesnt work. because i set the autocache when you edit the plugins.yaml.
