### ISSUE TITLE
自动补全的有偏移的情况, 我不知道是否是配置的问题

### ISSUE THREAD

**Issue by DestinyWang** [taigacute/ThinkVim#45]
我没有找到合适的解决方案, 具体的情况如下:

![image](https://user-images.githubusercontent.com/17758731/61425544-dbfcdf00-a949-11e9-8877-cedce019e7e0.png)

当开启自动补全时, 比如上图选择了 `base`, 但实际上 <CR> 之后选择的是下一个 `buildbaseresp`

![image](https://user-images.githubusercontent.com/17758731/61425607-064e9c80-a94a-11e9-8261-c37b59768d47.png)

**Comment by taigacute** [comment]
提供neovim版本。有必要填写issuetemplate 能给到我更多的信息

**Comment by taigacute** [comment]
python host 不同的环境有点不一样。
