### ISSUE TITLE
Code attribution

### ISSUE THREAD

**Issue by oblitum** [taigacute/ThinkVim#46]
Hi, I just noticed lots of code are copied from my `.vimrc` (which is now archived on GitHub, since I now use GitLab). Some code attribution is welcomed :)

Here's one example:

https://github.com/taigacute/ThinkVim/blob/972e147bff2306d0e61b0059606d294c8e514710/core/plugins/lightline.vim#L207-L231

vs

https://github.com/oblitum/dotfiles/blob/d9596530cc257ba1b4ad40b4beb0fa840e1ea7ed/.vimrc#L1298-L1322

**Comment by taigacute** [comment]
@oblitum   Hi, sorry for that. i used it for lightline, but i build my own statusline plugin spaceline.vim. it didnt use these code.i will remove
