### ISSUE TITLE
Spaceline update does not fit to tapbar.

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#48]
# Problems summary
After i update my fork with the latest version i saw that tabline is showing the empty tab with a number of `1` There should not be any tab before opening a file. 

## Environment Information

 * OS: MacOS 10.13.2

 * neovim `:version` output:
:version
NVIM v0.4.0-1021-gdd21cd2a4
Build type: Release
LuaJIT 2.0.5

 * `:checkhealth` or `:CheckHealth` result(neovim only):
Everything is ok.

## How to reproduce the problem from neovim startup (Required!)
Just try to open your thinkvim clone you will see the empty tab with a number of `1` before you opening a file.

## Screenshot (if possible)
![Screen Shot 2019-07-23 at 17 27 06](https://user-images.githubusercontent.com/7443948/61725287-cf282300-ad6f-11e9-8335-106c14469d49.png)

**Comment by taigacute** [comment]
you should copy the buftabline.vim to your plugin folder

**Comment by emeentag** [comment]
It is already there. Also is there a way to disable the spaceline.vim? I am not using onedark so it is not compatible with it yet. If there could be a way to deactivate it over local_settings, that would be awesome.

**Comment by taigacute** [comment]
the buftabline color is same as your background color..

**Comment by taigacute** [comment]
no update closed
