### ISSUE TITLE
Spaceline seperate style slant is broken

### ISSUE THREAD

**Issue by emeentag** [taigacute/ThinkVim#49]
# Problems summary
After i updated my local settings by adding `let g:spaceline_seperate_style = 'slant'` spaceline seems broken.

## Environment Information

 * OS: MacOS 10.13.2

 * neovim `:version` output:
NVIM v0.4.0-1021-gdd21cd2a4
Build type: Release
LuaJIT 2.0.5
 * `:checkhealth` or `:CheckHealth` result(neovim only):
All fine

## How to reproduce the problem from neovim startup (Required!)
add `let g:spaceline_seperate_style = 'slant'`  to your local settings.

## Screenshot (if possible)
![Screen Shot 2019-07-23 at 17 35 53](https://user-images.githubusercontent.com/7443948/61725604-62615880-ad70-11e9-981f-bd73b7f46cc9.png)
![Screen Shot 2019-07-23 at 17 36 25](https://user-images.githubusercontent.com/7443948/61725654-75742880-ad70-11e9-8ac6-77cf49e108ea.png)

**Comment by emeentag** [comment]
Actually all other styles are broken except arrow

**Comment by taigacute** [comment]
need restart nvim

**Comment by emeentag** [comment]
i did several times, might be a cahce?

**Comment by taigacute** [comment]
do you install it in your yaml ?

**Comment by taigacute** [comment]
@emeentag   i have improve git workflow see there https://github.com/taigacute/ThinkVim/wiki/Git-WorkFlow

**Comment by taigacute** [comment]
no update ..closed
