### ISSUE TITLE
vim-plug如何实现vim-which-key的懒加载

### ISSUE THREAD

**Issue by ppnman** [taigacute/ThinkVim#5]
你好，看了您的thinkvim收获很大。
但是有一个问题不知道如何解决，就是vim-which-key这个插件。这个插件需要在加载的时候执行一个注册操作。thinkvim是用dein管理插件的，并且用了一个钩子来实现在加载vim-which-key的时候，执行注册操作。
代码在这里：https://github.com/taigacute/ThinkVim/blob/8474b2831b0eb9919288e39d084a490471784485/rc/dein/deinlazy.toml#L14
请问vim-plug如何实现这样的操作呢？我看了vim-plug的教程，并没有钩子这个功能呀。。vim新手，问题太傻请见谅。

**Comment by taigacute** [comment]
@ppnman  `whichkey.vim`只是whichkey的设置 懒加载是同`on_cmd`，vim-plug也提供了on命令

**Comment by ppnman** [comment]
@taigacute 
很抱歉现在才看到您的回复。经过您的提示，已经解决了那个问题。

**Comment by taigacute** [comment]
happy hacking
