### ISSUE TITLE
typo in mappings.vim

### ISSUE THREAD

**Issue by haroldrandom** [taigacute/ThinkVim#8]
# Problems summary

typo in the line 38 of rc/mappings.vim, should be replaced by `window` like the screenshot

## Environment Information

 * OS: None

 * neovim `:version` output: None

 * `:checkhealth` or `:CheckHealth` result(neovim only): None

## How to reproduce the problem from neovim startup (Required!)

In the rc/mappings.vim

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/14357159/57195748-b9813980-6f88-11e9-839e-2a5fb11e02f0.png)

**Comment by taigacute** [comment]
fixed  thanks for issue
